### PR TITLE
Add CI/CD tests using Github Actions.

### PR DESCRIPTION
**Pull request by rb-anssi**
The tests compile and run the applet in the jcardsim Javacard simulator.
ECDSA signature tests are performed using OpenPGPpy, other tests such as
AES are performed using the local bin/smartpgp-cli script.

TODO: add tests for RSA, asymmetric encryption, pin modifications, secure
messaging (if well supported by jcardsim), etc.

### CODE REVIEW

**Comment by filip-zyzniewski** [comment]
Hi @rb-anssi, what's the story here? I was thinking about doing something similar and noticed this pull request - why does the progress on it seem to have stalled?

**Comment by rb-anssi** [comment]
Hi @filip-zyzniewski,

Maybe @af-anssi can comment on this to see why this PR is stalled.

Regards,

**Comment by af-anssi** [comment]
We really want to have CI tests for this project and we really appreciate the effort you put to initiate this move.
Integrating such tests requires:

1. to have a first PR on the javacard-3.0.1 branch (without ECC part which is not present in this branch), which is mandatory to ensure the tests run on 3.0.1 JCVM;
2. to merge the PR in 3.0.1 and to rebase the 3.0.4-without-secure-messaging branch;
3. to have a second PR to integrate ECC tests on the 3.0.4-without-secure-messaging branch.

I did not find the time yet to rework the PR and to integrate missing tests.

**Comment by af-anssi** [comment]
I have integrated a revised version of this PR in javacard-3.0.1 branch (see https://github.com/ANSSI-FR/SmartPGP/commit/0b43929a830133e0d3c568f35f387feade8a557a and https://github.com/ANSSI-FR/SmartPGP/commit/e84853414f7d12145641c3b1b20e1de6c4170c9d) with new signature and decryption tests for RSA and a decryption test for ECC.
All branches have been rebased, and ECC tests only activated for javacard-3.0.4 versions.
Does it seem OK to both of you ?

**Comment by rb-anssi** [comment]
Hi @af-anssi : seems all good on my side!

**Comment by af-anssi** [comment]
This PR has been handled.

**Pull request closed without merging**
